export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_DIALOGS = 'LOAD_DIALOGS';
export const LOAD_MORE_DIALOGS = 'LOAD_MORE_DIALOGS';
export const SET_ACTIVE_DIALOG = 'SET_ACTIVE_DIALOG';
export const SET_USERS_INFO = 'SET_USERS_INFO';
export const CHANGE_DIALOG_FINDING_PARAMS = 'CHANGE_DIALOG_FINDING_PARAMS';
export const SET_CHANNELS = 'SET_CHANNELS';
